[project]
name = 'bitgear-world'
description = ''
authors = []
telemetry = false
cache_dir = '.cache'
requirements = []
[contracts.bitgear-genesis]
path = 'contracts/bitgear-genesis.clar'
clarity_version = 1
epoch = 2.0

[contracts.bitgear-genesis-slots]
path = 'contracts/bitgear-genesis-slots.clar'
clarity_version = 1
epoch = 2.0

[contracts.bitgear-traits-v0]
path = 'contracts/bitgear-traits-v0.clar'
clarity_version = 1
epoch = 2.0

[contracts.bitgear-traits-v1]
path = 'contracts/bitgear-traits-v1.clar'
clarity_version = 1
epoch = 2.0

[contracts.byte-fighters]
path = 'contracts/byte-fighters.clar'
clarity_version = 1
epoch = 2.0

[contracts.equipment-v0]
path = 'contracts/equipment-v0.clar'
clarity_version = 1
epoch = 2.0

[contracts.nft-trait]
path = 'contracts/nft-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.player-character-v0]
path = 'contracts/player-character-v0.clar'
clarity_version = 1
epoch = 2.0

[contracts.quest]
path = 'contracts/quest.clar'
clarity_version = 1
epoch = 2.0

[contracts.woodlands-v0]
path = 'contracts/woodlands-v0.clar'
clarity_version = 1
epoch = 2.0
[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
