[project]
name = "bitgear-world"
requirements = []
costs_version = 1

[contracts.nft-trait]
path = "contracts/nft-trait.clar"
depends_on = []

[contracts.bitgear-genesis]
path = "contracts/bitgear-genesis.clar"
depends_on = ["nft-trait"]

[contracts.byte-fighters]
path = "contracts/byte-fighters.clar"
depends_on = ["nft-trait"]

[contracts.bitgear-traits-v0]
path = "contracts/bitgear-traits-v0.clar"
depends_on = ["nft-trait"]

[contracts.bitgear-traits-v1]
path = "contracts/bitgear-traits-v1.clar"
depends_on = ["nft-trait"]

[contracts.player-character-v0]
path = "contracts/player-character-v0.clar"
depends_on = ["bitgear-genesis", "bitgear-traits-v0", "byte-fighters", "equipment-v0"]

[contracts.equipment-v0]
path = "contracts/equipment-v0.clar"
depends_on = ["bitgear-traits-v1"]

[contracts.bitgear-genesis-slots]
path = "contracts/bitgear-genesis-slots.clar"
depends_on = ["bitgear-traits-v1"]

[contracts.woodlands-v0]
path = "contracts/woodlands-v0.clar"
depends_on = []