on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Check contract'
        uses: docker://hirosystems/clarinet:latest
        with:
          entrypoint: 'bash'
          args: -c "cd bitgear-nft-contract && clarinet check"
      - name: 'Execute test suite'
        uses: docker://hirosystems/clarinet:latest
        with:
          entrypoint: 'bash'
          args: -c "cd bitgear-nft-contract && clarinet test"
      - name: 'Export code coverage'
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.lcov
          verbose: true
